[package]
name = "settlement"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "23.0.0-rc.2.2"

[dev-dependencies]
soroban-sdk = { version = "23.0.0-rc.2.2", features = ["testutils"] }
